### ISSUE TITLE
Support `dbt-external-tables`

### ISSUE THREAD

**Issue by connor-charles** [autotraderuk/dbt-dry-run#24]
The dry runner will fail if a source table is created by the package `dbt-external-tables` if the source table will not exist yet.

Need to interpret the [external](https://docs.getdbt.com/reference/resource-properties/external) field in the model metadata.

Goal for AT here is to use the package [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables/blob/main/sample_sources/bigquery.yml) with Bigtable tables. But this has other use cases for people uses gcs or other data sources as well.

**Comment by connor-charles** [comment]
Here is a mockup of what the `external` attribute might look like for a highly nested schema (In this case this was for a Bigtable external table):

```yaml
      - name: src_identity
        external:
          location: this is still a required property, but it will be ignored
          options:
            format: cloud_bigtable
            uris:
              - "https://googleapis.com/bigtable/projects/<URI_TO_TABLE>"
            bigtable_options: '{ columnFamilies: [{"familyId": "ids", "type": "STRING", "encoding": "BINARY"}], readRowkeyAsString: true, onlyReadLatest: true}'

        columns:
          - name: row_key
            data_type: STRING
          - name: events
            data_type: RECORD[]
          - name: events.column
            data_type: RECORD[]
          - name: events.column.name
            data_type: STRING
          - name: events.column.cell
            data_type: RECORD[]
          - name: events.column.cell.value
            data_type: STRING
          - name: events.column.timestamp
            data_type: TIMESTAMP
```

Here the dry runner would interpret any `data_type` ending in `[]` as a `REPEATED` column mode. `RECORD` columns don't have types per say but this is just an indication that the dry runner should expect sub fields. Then the dry runner would convert this yaml definition into a `SELECT` literal which can be used for downstream `refs` for this source.
