### ISSUE TITLE
Allow configurable extra metadata to enable `dry_run.check_columns`

### ISSUE THREAD

**Issue by connor-charles** [autotraderuk/dbt-dry-run#35]
Currently the way to enable `check_columns` is by adding the following to a model or dataset's metadata:

```
models:
  - name: badly_documented_model
    description: This model is missing some columns in its docs
    meta:
      dry_run.check_columns: true
```

However it might be the case that you wish to use other metadata to enable/disable the check columns. At Auto Trader we have some specific metadata for data governance to mark a model as an ODP.

```
models:
  - name: badly_documented_model
    description: This model is missing some columns in its docs
    meta:
      data_governance.can_be_referenced: true
```

We would like this to also enable `check_columns`. This issue is to implement a new CLI Parameter called `--check-columns-metadata-key` which will create extra check columns metadata. So for example adding the parameter:

```
--check-columns-metadata-key=data_governance.can_be_referenced
```

Will mean that either `dry_run.check_columns` or `data_governance.can_be_referenced` will enable the check_columns for this metadata.

To resolve possible conflicts in metadata such as:

```
  - name: my_model
    description: Some model
    meta:
      data_governance.can_be_referenced: False
      dry_run.check_columns: True
```

Then we should always take the value of `dry_run.check_columns` if it is specified and fall back to `can_be_referenced` if it is there.
